name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Build FFmpeg
      working-directory: ./media/libraries/decoder_ffmpeg/src/main/jni
      run: ./build_ffmpeg.sh ./media/libraries/decoder_ffmpeg/src/main ${{ steps.setup-ndk.outputs.ndk-path }} "linux-x86_64" 21 "mp3 aac ac3 eac3 dca truehd mlp vorbis opus flac alac pcm_mulaw pcm_alaw"

    - name: Build with Gradle
      working-directory: ./leanfront
      run: ./gradlew build

